export interface F1Driver {
  nameKr: string
  nameEn: string
  num: string
  image: string
  nationalityKr: string
  nationalityFlag: string
  age: number
  careerKr: string
  point2026Kr: string
  storyKr: string
}

export interface F1Team {
  id: string
  nameKr: string
  nameShort: string
  fullName: string
  color: string
  teamFlag: string
  teamCountry: string
  logo: string
  drivers: [F1Driver, F1Driver]
  trait: string
  watchPoint: string
}

export const F1_TEAMS: F1Team[] = [
  {
    id: 'redbull',
    nameKr: '레드불 레이싱',
    nameShort: 'RBR',
    fullName: 'ORACLE RED BULL RACING',
    color: '#3671C6',
    teamFlag: '🇦🇹',
    teamCountry: '오스트리아',
    logo: 'https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000001/common/f1/2025/redbullracing/2025redbullracinglogo.webp',
    trait: '에너지드링크 회사 레드불이 2005년 재규어 레이싱을 인수해 만든 팀으로 베텔·베르스타펜 두 명의 월드 챔피언을 탄생시켰습니다. 2026년엔 혼다 파워유닛과 결별하고 포드와 함께 만든 첫 자체 파워유닛으로, 새 규정 첫해를 정면 돌파합니다.',
    watchPoint: '챔피언에게 주어지는 1번을 노리스에게 내준 베르스타펜이 #3을 달고 반격합니다. 18세 최연소 우승, 한 시즌 19승의 기록 보유자죠. 21살 신예 하자르가 그 옆자리를 버텨낼지도 관전 포인트입니다.',
    drivers: [
      {
        nameKr: '막스 베르스타펜',
        nameEn: 'Max Verstappen',
        num: '3',
        image: '/images/f1/Max-Verstappen.avif',
        nationalityKr: '네덜란드',
        nationalityFlag: '🇳🇱',
        age: 28,
        careerKr: '2021~2024 4년 연속 월드챔피언. 역대 최다승 페이스를 달리는 현 세대 최강자.',
        point2026Kr: '챔피언 번호 #1을 노리스에게 내주고 #3으로 반격하는 시즌. 새 엔진 규정에서도 정상을 지킬 수 있을지.',
        storyKr: '이기는 게 디폴트인 남자, 그 디폴트가 흔들린 첫 시즌.',
      },
      {
        nameKr: '아이작 하자르',
        nameEn: 'Isack Hadjar',
        num: '6',
        image: '/images/f1/Isack-Hadjar.avif',
        nationalityKr: '프랑스',
        nationalityFlag: '🇫🇷',
        age: 21,
        careerKr: '2025 레이싱 불스 데뷔 후 강렬한 인상을 남기며 1년 만에 레드불 메인팀 승격.',
        point2026Kr: '베르스타펜의 새 팀메이트. 역대 레드불 2번 시트의 주인공들은 항상 혹독한 압박을 받았다.',
        storyKr: '베르스타펜 옆자리는 F1에서 가장 위험한 의자다. 그 의자에 21살이 앉았다.',
      },
    ],
  },
  {
    id: 'ferrari',
    nameKr: '스쿠데리아 페라리',
    nameShort: 'SF',
    fullName: 'SCUDERIA FERRARI',
    color: '#E8002D',
    teamFlag: '🇮🇹',
    teamCountry: '이탈리아',
    logo: 'https://media.formula1.com/image/upload/c_lfill,w_48/q_auto/v1740000001/common/f1/2026/ferrari/2026ferrarilogo.webp',
    trait: 'F1 창립 이래 한 번도 빠지지 않은 유일한 팀이자 가장 많은 우승을 기록한 명문. 2025년 7회 챔피언 해밀턴이 합류해 르클레르와 슈퍼팀을 이뤘습니다.',
    watchPoint: '전 세계에서 가장 팬이 많은 팀(티포시). 빨간 차가 앞서면 관중석이 들썩입니다. 해밀턴 vs 르클레르 팀 내 신경전이 시즌 내내 이어집니다.',
    drivers: [
      {
        nameKr: '샤를 르클레르',
        nameEn: 'Charles Leclerc',
        num: '16',
        image: '/images/f1/Charles-Leclerc.avif',
        nationalityKr: '모나코',
        nationalityFlag: '🇲🇨',
        age: 28,
        careerKr: '페라리의 에이스. 폴포지션의 제왕으로 불리지만 아직 월드타이틀은 없다.',
        point2026Kr: '해밀턴과의 팀 내 자존심 대결 2년차. 페라리 우승 갈증을 풀 적기.',
        storyKr: '고향 모나코에서 우승하는 게 꿈인 남자, 페라리의 마지막 희망.',
      },
      {
        nameKr: '루이스 해밀턴',
        nameEn: 'Lewis Hamilton',
        num: '44',
        image: '/images/f1/Lewis-Hamilton.avif',
        nationalityKr: '영국',
        nationalityFlag: '🇬🇧',
        age: 41,
        careerKr: '역대 최다 7회 월드챔피언. 2025년 메르세데스를 떠나 페라리로 충격 이적했다.',
        point2026Kr: '페라리 2년차, 빨간 차로 8번째 타이틀 도전. 커리어 마지막 불꽃.',
        storyKr: '전설이 빨간 차를 입었다. 동화의 결말은 우승일까.',
      },
    ],
  },
  {
    id: 'mercedes',
    nameKr: '메르세데스',
    nameShort: 'AMG',
    fullName: 'MERCEDES-AMG PETRONAS',
    color: '#27F4D2',
    teamFlag: '🇩🇪',
    teamCountry: '독일',
    logo: 'https://media.formula1.com/image/upload/c_lfill,w_48/q_auto/v1740000001/common/f1/2026/mercedes/2026mercedeslogo.webp',
    trait: '2014~2021 터보 하이브리드 시대를 지배한 8연속 컨스트럭터 챔피언. 해밀턴이 떠난 뒤 러셀이 리더가 됐고, 18세 신성 안토넬리가 미래를 짊어집니다.',
    watchPoint: '2026 엔진 규정 변화에서 메르세데스 파워유닛이 가장 강할 거란 예측이 많아요. 엔진 경쟁력이 부활하는지 지켜보세요.',
    drivers: [
      {
        nameKr: '조지 러셀',
        nameEn: 'George Russell',
        num: '63',
        image: '/images/f1/George-Russell.avif',
        nationalityKr: '영국',
        nationalityFlag: '🇬🇧',
        age: 28,
        careerKr: '메르세데스의 리더. 침착한 레이스 운영과 기술적 피드백이 강점.',
        point2026Kr: '해밀턴이 떠난 자리, 팀의 명실상부한 에이스. 새 규정에서 메르세데스 부활의 선봉.',
        storyKr: '해밀턴이 떠난 자리, 이제 팀의 미래는 그의 손에.',
      },
      {
        nameKr: '키미 안토넬리',
        nameEn: 'Kimi Antonelli',
        num: '12',
        image: '/images/f1/Kimi-Antonelli.avif',
        nationalityKr: '이탈리아',
        nationalityFlag: '🇮🇹',
        age: 19,
        careerKr: '2025년 메르세데스로 데뷔한 이탈리아 천재. 데뷔 시즌부터 포디움을 경험했다.',
        point2026Kr: '10대 후반의 차세대 슈퍼스타. 2년차에 첫 우승이 나올지.',
        storyKr: '이탈리아가 30년 만에 기다린 슈퍼스타, 이제 막 시작했다.',
      },
    ],
  },
  {
    id: 'mclaren',
    nameKr: '맥라렌',
    nameShort: 'MCL',
    fullName: 'McLAREN FORMULA 1 TEAM',
    color: '#FF8000',
    teamFlag: '🇬🇧',
    teamCountry: '영국',
    logo: 'https://media.formula1.com/image/upload/c_lfill,w_48/q_auto/v1740000001/common/f1/2026/mclaren/2026mclarenlogo.webp',
    trait: '2024~2025 컨스트럭터 챔피언을 거머쥔 현재의 최강팀. 노리스와 피아스트리, 둘 다 우승 가능한 젊은 듀오로 가장 균형 잡힌 라인업을 자랑합니다.',
    watchPoint: '팀메이트 둘이 실력이 비슷해 매 경기 진짜 싸움이 벌어집니다. 같은 차로 누가 더 빠른지 보는 가장 순수한 재미가 있어요.',
    drivers: [
      {
        nameKr: '랜도 노리스',
        nameEn: 'Lando Norris',
        num: '1',
        image: '/images/f1/Lando-Norris.avif',
        nationalityKr: '영국',
        nationalityFlag: '🇬🇧',
        age: 26,
        careerKr: '2025년 첫 월드챔피언에 등극. 데뷔 7년 만에 정상에 올랐다.',
        point2026Kr: '챔피언 번호 #1을 처음 단 시즌. 1회 우승이 우연이 아님을 증명할 차례.',
        storyKr: '오래 기다린 챔피언, 이제 사냥당하는 입장이 되었다.',
      },
      {
        nameKr: '오스카 피아스트리',
        nameEn: 'Oscar Piastri',
        num: '81',
        image: '/images/f1/Oscar-Piastri.avif',
        nationalityKr: '호주',
        nationalityFlag: '🇦🇺',
        age: 24,
        careerKr: '냉정한 호주인. 팀메이트 노리스와 마지막까지 타이틀을 다툰 강자.',
        point2026Kr: '아쉽게 놓친 타이틀, 2026엔 팀 내 1인자 자리를 노린다.',
        storyKr: '표정 없는 암살자, 같은 팀 챔피언을 무너뜨리려 한다.',
      },
    ],
  },
  {
    id: 'aston',
    nameKr: '애스턴 마틴',
    nameShort: 'AMR',
    fullName: 'ASTON MARTIN ARAMCO',
    color: '#229971',
    teamFlag: '🇬🇧',
    teamCountry: '영국',
    logo: 'https://media.formula1.com/image/upload/c_lfill,w_48/q_auto/v1740000001/common/f1/2026/astonmartin/2026astonmartinlogo.webp',
    trait: '2026년 전설적 설계자 에이드리언 뉴이가 합류하고 혼다 워크스 엔진을 쓰는 다크호스. 2회 챔피언 알론소의 노련함이 팀을 끌어올립니다.',
    watchPoint: '알론소는 44세에도 가장 영리한 드라이버로 꼽혀요. 뉴이의 신차가 통하면 단숨에 우승권으로 도약할 수 있는 팀입니다.',
    drivers: [
      {
        nameKr: '페르난도 알론소',
        nameEn: 'Fernando Alonso',
        num: '14',
        image: '/images/f1/Fernando Alonso.avif',
        nationalityKr: '스페인',
        nationalityFlag: '🇪🇸',
        age: 44,
        careerKr: '2005·2006 월드챔피언. 그리드 최고령이자 살아있는 전설.',
        point2026Kr: '뉴이가 설계한 새 차로 마지막 우승 도전. 나이는 숫자일 뿐.',
        storyKr: '20년 전 챔피언이 아직도 그리드에 있다. 그 이유가 있다.',
      },
      {
        nameKr: '랜스 스트롤',
        nameEn: 'Lance Stroll',
        num: '18',
        image: '/images/f1/Lance-Stroll.avif',
        nationalityKr: '캐나다',
        nationalityFlag: '🇨🇦',
        age: 27,
        careerKr: '팀 오너의 아들이자 베테랑. 빗길에서 번뜩이는 스피드를 보인다.',
        point2026Kr: '알론소라는 거대한 잣대 옆에서 자신의 가치를 증명해야 하는 시즌.',
        storyKr: '아버지가 산 팀, 실력으로 자리를 지켜야 하는 부담.',
      },
    ],
  },
  {
    id: 'alpine',
    nameKr: '알핀',
    nameShort: 'ALP',
    fullName: 'BWT ALPINE F1 TEAM',
    color: '#0093CC',
    teamFlag: '🇫🇷',
    teamCountry: '프랑스',
    logo: 'https://media.formula1.com/image/upload/c_lfill,w_48/q_auto/v1740000001/common/f1/2026/alpine/2026alpinelogo.webp',
    trait: '르노 그룹이 소유한 프랑스 국적 팀. 2026년부터 자체 엔진을 포기하고 메르세데스 엔진으로 전환해 중위권 반등을 노립니다.',
    watchPoint: '프랑스 유일의 팩토리 팀이라는 자존심. 가슬리가 중위권에서 보여주는 알뜰한 포인트 사냥을 지켜보세요.',
    drivers: [
      {
        nameKr: '피에르 가슬리',
        nameEn: 'Pierre Gasly',
        num: '10',
        image: '/images/f1/Pierre-Gasly.avif',
        nationalityKr: '프랑스',
        nationalityFlag: '🇫🇷',
        age: 30,
        careerKr: '2020 몬차에서 깜짝 우승한 프랑스 에이스. 중위권에서 빛나는 실력자.',
        point2026Kr: '프랑스 국민팀 알핀의 리더. 중위권 탈출을 이끄는 베테랑.',
        storyKr: '한 번의 기적 같은 우승, 그 순간을 다시 만들 수 있을까.',
      },
      {
        nameKr: '프랑코 콜라핀토',
        nameEn: 'Franco Colapinto',
        num: '43',
        image: '/images/f1/Franco-Colapinto.avif',
        nationalityKr: '아르헨티나',
        nationalityFlag: '🇦🇷',
        age: 22,
        careerKr: '2024년 윌리엄스에서 깜짝 데뷔, 아르헨티나의 새 영웅으로 떠올랐다.',
        point2026Kr: '정규 시트를 확보한 첫 풀시즌. 열정적인 남미 팬덤의 기대.',
        storyKr: '메시의 나라가 F1에서 다시 응원할 이름을 찾았다.',
      },
    ],
  },
  {
    id: 'williams',
    nameKr: '윌리엄스',
    nameShort: 'WIL',
    fullName: 'WILLIAMS RACING',
    color: '#64C4FF',
    teamFlag: '🇬🇧',
    teamCountry: '영국',
    logo: 'https://media.formula1.com/image/upload/c_lfill,w_48/q_auto/v1740000001/common/f1/2026/williams/2026williamslogo.webp',
    trait: '9회 컨스트럭터 챔피언의 유서 깊은 명문이지만 최근엔 하위권. 2025년 페라리 출신 사인츠를 영입하며 중위권 복귀에 시동을 걸었습니다.',
    watchPoint: '한때 세나가 몰던 전통의 강호. 사인츠가 옛 명문을 되살릴 수 있을지가 시즌 내내 흥미로운 스토리입니다.',
    drivers: [
      {
        nameKr: '알렉스 알본',
        nameEn: 'Alex Albon',
        num: '23',
        image: '/images/f1/Alexander-Albon.avif',
        nationalityKr: '태국',
        nationalityFlag: '🇹🇭',
        age: 29,
        careerKr: '레드불에서 방출됐다 부활한 입지전적 인물. 윌리엄스의 기둥.',
        point2026Kr: '사인츠와 함께 명문팀 윌리엄스의 부활을 이끄는 핵심.',
        storyKr: '한 번 버려졌던 드라이버, 가장 끈질긴 부활 스토리.',
      },
      {
        nameKr: '카를로스 사인츠',
        nameEn: 'Carlos Sainz',
        num: '55',
        image: '/images/f1/Carlos-Sainz.avif',
        nationalityKr: '스페인',
        nationalityFlag: '🇪🇸',
        age: 31,
        careerKr: "페라리에서 우승을 거둔 검증된 승부사. 별명은 '스무스 오퍼레이터'.",
        point2026Kr: '윌리엄스에서 명문팀 재건 프로젝트 2년차. 리더십이 관건.',
        storyKr: '페라리를 떠나 전통의 명가 재건에 인생을 건 베테랑.',
      },
    ],
  },
  {
    id: 'rb',
    nameKr: '레이싱 불스',
    nameShort: 'RB',
    fullName: 'VISA CASH APP RB',
    color: '#6692FF',
    teamFlag: '🇮🇹',
    teamCountry: '이탈리아',
    logo: 'https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000001/common/f1/2026/racingbulls/2026racingbullslogo.webp',
    trait: '레드불의 자매팀(B팀). 레드불 본팀으로 올라갈 영 드라이버를 키우는 육성소 역할을 합니다. 본팀과 부품을 일부 공유해요.',
    watchPoint: '여기서 잘하면 레드불 본팀으로 승격됩니다. 미래의 스타가 누구인지 가장 먼저 볼 수 있는 팀이에요.',
    drivers: [
      {
        nameKr: '리암 로슨',
        nameEn: 'Liam Lawson',
        num: '30',
        image: '/images/f1/Liam-Lawson.avif',
        nationalityKr: '뉴질랜드',
        nationalityFlag: '🇳🇿',
        age: 24,
        careerKr: '2025년 레드불 메인팀에서 강등의 아픔을 겪고 레이싱 불스로 복귀.',
        point2026Kr: '재기를 노리는 시즌. 다시 메인팀으로 올라갈 마지막 기회일 수 있다.',
        storyKr: '정상 문턱에서 밀려난 청년, 증명할 시간은 많지 않다.',
      },
      {
        nameKr: '아비드 린드블라드',
        nameEn: 'Arvid Lindblad',
        num: '41',
        image: '/images/f1/Arvid-Lindblad.avif',
        nationalityKr: '영국',
        nationalityFlag: '🇬🇧',
        age: 18,
        careerKr: '2026 그리드 유일의 루키. 레드불 주니어 출신의 초고속 유망주.',
        point2026Kr: "그리드 유일의 신인. '차세대 베르스타펜'이라 불리는 재능의 데뷔 무대.",
        storyKr: "18살, F1 유일의 신입생. 모두가 '제2의 베르스타펜'을 기대한다.",
      },
    ],
  },
  {
    id: 'haas',
    nameKr: '하스',
    nameShort: 'HAS',
    fullName: 'MoneyGram HAAS F1 TEAM',
    color: '#B6BABD',
    teamFlag: '🇺🇸',
    teamCountry: '미국',
    logo: 'https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000001/common/f1/2026/haas/2026haaslogo.webp',
    trait: '가장 작은 예산으로 운영되는 미국 팀. 페라리의 엔진과 다수 부품을 사 와 효율적으로 차를 만드는 알뜰 운영의 대명사입니다.',
    watchPoint: '적은 돈으로 거대 팀들과 싸우는 언더독. 가끔 터지는 깜짝 입상이 이 팀을 응원하게 만드는 매력이에요.',
    drivers: [
      {
        nameKr: '에스테반 오콘',
        nameEn: 'Esteban Ocon',
        num: '31',
        image: '/images/f1/Esteban-Ocon.avif',
        nationalityKr: '프랑스',
        nationalityFlag: '🇫🇷',
        age: 29,
        careerKr: '2021 헝가리에서 우승한 프랑스인. 끈질긴 디펜스의 달인.',
        point2026Kr: '베어먼이라는 신예와 짝을 이뤄 하스의 중원 도약을 견인.',
        storyKr: '딱 한 번 우승, 그 한 번을 위해 누구보다 치열하게 싸운다.',
      },
      {
        nameKr: '올리버 베어먼',
        nameEn: 'Oliver Bearman',
        num: '87',
        image: '/images/f1/Oliver-Bearman.avif',
        nationalityKr: '영국',
        nationalityFlag: '🇬🇧',
        age: 20,
        careerKr: '어린 나이에 대체 출전으로 강한 인상을 남긴 영국 유망주.',
        point2026Kr: '풀시즌 2년차, 미래의 톱팀 자리를 노리는 영건의 본격 도약기.',
        storyKr: '땜빵 출전에서 미래의 스타로, 가족 생일을 번호 #87에 새긴 청년.',
      },
    ],
  },
  {
    id: 'audi',
    nameKr: '아우디',
    nameShort: 'AUD',
    fullName: 'AUDI F1 TEAM (ex-SAUBER)',
    color: '#F50537',
    teamFlag: '🇩🇪',
    teamCountry: '독일',
    logo: 'https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000001/common/f1/2026/audi/2026audilogo.webp',
    trait: '기존 킥 자우버가 2026년부터 완전한 아우디 워크스 팀으로 전환. 독일 자동차 거인이 자체 엔진을 들고 F1에 정식 진입하는 빅 프로젝트입니다.',
    watchPoint: '대형 제조사의 신규 진입은 보통 몇 년의 적응기가 필요해요. 아우디가 얼마나 빨리 경쟁력을 갖추는지가 장기 관전 포인트.',
    drivers: [
      {
        nameKr: '니코 휠켄베르크',
        nameEn: 'Nico Hülkenberg',
        num: '27',
        image: '/images/f1/Nico-Hulkenberg.avif',
        nationalityKr: '독일',
        nationalityFlag: '🇩🇪',
        age: 38,
        careerKr: '최다 출전 무포디움 기록을 끝내 깬 베테랑. 풍부한 경험의 소유자.',
        point2026Kr: '아우디 워크스 원년의 리더. 새 출발하는 명가의 길잡이.',
        storyKr: '200전 만에 첫 포디움, 끈기의 화신이 새 역사의 첫 페이지를 쓴다.',
      },
      {
        nameKr: '가브리엘 보르톨레토',
        nameEn: 'Gabriel Bortoleto',
        num: '5',
        image: '/images/f1/Gabriel Bortoleto.avif',
        nationalityKr: '브라질',
        nationalityFlag: '🇧🇷',
        age: 21,
        careerKr: 'F2·F3 연속 챔피언 출신. 브라질이 기대하는 차세대 스타.',
        point2026Kr: '아우디 프로젝트의 미래. 브라질 팬들의 새로운 희망.',
        storyKr: '세나의 나라가 오래 기다린 차세대 챔피언 후보.',
      },
    ],
  },
  {
    id: 'cadillac',
    nameKr: '캐딜락',
    nameShort: 'CAD',
    fullName: 'CADILLAC F1 TEAM',
    color: '#8B0000',
    teamFlag: '🇺🇸',
    teamCountry: '미국',
    logo: 'https://media.formula1.com/image/upload/c_fit,h_64/q_auto/v1740000001/common/f1/2026/cadillac/2026cadillaclogo.webp',
    trait: '2026년 새로 합류하는 11번째 팀. GM 캐딜락 브랜드로 참가하며 베테랑 페레스와 보타스를 영입해 신생팀의 약점인 경험 부족을 메웠습니다.',
    watchPoint: '완전한 신생팀이 첫 시즌 어떻게 살아남는지 보는 것 자체가 역사적인 장면. 베테랑 듀오의 노련함이 핵심입니다.',
    drivers: [
      {
        nameKr: '세르히오 페레스',
        nameEn: 'Sergio Perez',
        num: '11',
        image: '/images/f1/Sergio-Perez.avif',
        nationalityKr: '멕시코',
        nationalityFlag: '🇲🇽',
        age: 36,
        careerKr: '통산 다승 베테랑. 레드불에서 베르스타펜의 윙맨으로 활약했다.',
        point2026Kr: '신생 캐딜락의 간판으로 화려하게 복귀. 베테랑의 경험으로 새 팀을 이끈다.',
        storyKr: '은퇴한 줄 알았던 베테랑, 미국의 신생팀이 그를 다시 불러냈다.',
      },
      {
        nameKr: '발테리 보타스',
        nameEn: 'Valtteri Bottas',
        num: '77',
        image: '/images/f1/Valtteri-Bottas.avif',
        nationalityKr: '핀란드',
        nationalityFlag: '🇫🇮',
        age: 36,
        careerKr: '메르세데스 시절 다수 우승. 해밀턴의 팀메이트로 황금기를 함께했다.',
        point2026Kr: '페레스와 함께 캐딜락의 신생 도전을 이끄는 노련한 듀오.',
        storyKr: '한 시대를 떠받친 2인자, 새 팀에서 다시 주인공을 꿈꾼다.',
      },
    ],
  },
]
